### ISSUE TITLE
:NextError jumps between top and bottom buffer

### ISSUE THREAD

**Issue by i-terzic** [ej-shafran/compile-mode.nvim#14]
**Describe the bug**
The respectable error causing code is opened in different buffers. Switching between top and bottom in my case.

**To Reproduce**
1. Run `:Recompile` or `:Compile`
   **Note**: There should be more than 2 compilation warnings/errors
2. Run `:NextError` multiple times 

**Expected behavior**
The errors should be opened in the same window/buffer and not jump arround from top to bottom and so on. Also i would expect the compilation errors (the temporary buffer) to stay open for further error information.

**Screenshots**

**Neovim Version**
Include the result of `nvim -v`:

```
v0.9.4
```

**compile-mode.nvim Version**
Specify what version of `compile-mode.nvim` you are using.

```
latest
```

**Additional context**

I use `make` and `cc` for compiling the code.
Also i am running neovim inside WSL. 

C code for testing: 
```c
#include <stdio.h>

int main(void)
{

    int i = 17;
    int *ip = &i;
    char *cp;
    char *cp1;
    void *vp1;
    void *vp2;

    printf("ip1: pointer: %p, value: %d\n", (void *) ip, *ip);

    return 0;
}
```

**Comment by ej-shafran** [comment]
Will give this a look and try to fix.

**Comment by i-terzic** [comment]
![2024-02-27_13h22_56](https://github.com/ej-shafran/compile-mode.nvim/assets/91913247/b9cc70f6-45d4-40fc-b1d2-6dd4477c34bf)
I hope this video illustrates the issue fine. :)

**Comment by ej-shafran** [comment]
Just checking - are you using the [`same_window_errors`](https://github.com/ej-shafran/compile-mode.nvim?tab=readme-ov-file#same_window_errors) config option? Maybe check it out and see if it's what you're looking for?

**Comment by i-terzic** [comment]
Sort of, is there an (automatic) option to use/open the respective buffer below the compilation output to keep the info of the compilations errors open? When running `:Compile` and `:NextError` e.g. while `Netrw` is open the info of the errors is lost. I guess it will be more of a convenience feature, than a bug. I would expect the temporary buffer to stay at the top and open, and `:NextError` to open the respecive buffer/location below.

**Comment by i-terzic** [comment]
I think retaning the focus on the buffer in which you run the command in combination with `same_window_errors` should fix the issue right there. Maybe adding that as a configuration option for that will improve the convenience (in my opinion). What do you think of that idea?

**Comment by ej-shafran** [comment]
I see... So what you're looking for would be like the behavior of
- Running `:Compile` with your command
- Navigating back to the file explorer or some other buffer
- Running `:NextError` there

Such that the top window shows the compilation buffer, and the bottom window shows the location of the error?

**Comment by i-terzic** [comment]
Actually, i'm looking for the option that the compilation buffer will stay open when i run :NextError, so if there are multiple compilation errors, i don't loose sight of whats the issue there. Since the buffer is opened vertically on top, i would expect :NextError to open the repective malicious code in the window below and keep the compilation buffer open at the same time.

**Comment by ej-shafran** [comment]
Well, with `same_window_errors`, `:NextError` opens the error in the buffer which the cursor is currently on.

How about trying:

```vimscript
autocmd FileType compilation wincmd w
```

or

```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "compilation",
  command = "wincmd w",
})
```

To not switch focus to the compilation buffer once its created? Try it and see if it fits what you're looking for?

**Comment by i-terzic** [comment]
Thats exactly what i was looking for. Thank you for the support!
