### ISSUE TITLE
Invalid buffer id: -1

### ISSUE THREAD

**Issue by vunhatchuong** [ej-shafran/compile-mode.nvim#23]
**Describe the bug**
When I run `:Compile` every time **after** the 1st time the error always appears.

**To Reproduce**
1. Open a buffer
2. Run `:Compile`
3. Type `zig build`

**Expected behavior**
The compile buffer opens and run the command.

**Screenshots**
![image](https://github.com/user-attachments/assets/7a0a0e89-ab71-4f6b-978e-00812ac9f3e8)

**Neovim Version**

```
v0.10.1
```

**compile-mode.nvim Version**
v4.0.0

**Additional context**
![image](https://github.com/user-attachments/assets/61899390-dc6a-4849-970b-d632ecc60a27)

**Comment by ej-shafran** [comment]
Thanks for letting me know! Will fix this soon

**Comment by ej-shafran** [comment]
Hi @vunhatchuong - I can't seem to reproduce your bug... Do you mind sharing your compile-mode configuration? Or trying to reproduce this with a minimal config?

**Comment by vunhatchuong** [comment]
```lua
{
  "ej-shafran/compile-mode.nvim",
  cmd = { "Compile", "Recompile" },
  dependencies = {
      "nvim-lua/plenary.nvim",
  },
  keys = {
      { "<leader>ox", "<cmd>Compile<cr>", desc = "Compile" },
      {
          "<leader>or",
          function()
              vim.cmd("Recompile")
          end,
          desc = "Compile",
      },
  },
  config = function()
      vim.g.compile_mode = {}
  end,
},
```

There's some interesting thing here:

- I **always** get the bug if I use those keybinds.
- If I lazy load with the cmds, only the first time I run **don't** have the bug.
- If I lazy load with the cmds, cancel it and use the keybinds, I still get the bug.
- Also seems like it only bug on Windows lol, I tested on Arch VM and it's fine.

**Comment by vunhatchuong** [comment]
Changing every instance of `bufnr` to `0` thus reverting [this](https://github.com/ej-shafran/compile-mode.nvim/commit/e78d79f278c837254bf0beb033e554a1a8538aa2) commit "fixes" it.

**Comment by vunhatchuong** [comment]
The doc of [vim.fn.bufnr](https://neovim.io/doc/user/builtin.html#bufnr()) stated that it will return `-1` (like my bug) if the buffer doesn't exist. 

Seems like Windows doesn't like buffer name with `*` **prefix**.

So these will work:

```lua
vim.g.compile_mode = {
    buffer_name = "*compilation",
    -- buffer_name = "compilation",
}
```

But not:

```lua
vim.g.compile_mode = {
    buffer_name = "compilation*",
}
```

**Comment by vunhatchuong** [comment]
So remove `vim.fn.fnameescape` fixes the problem:

```diff
ftplugin/compilation.lua:4

- local bufnr = vim.fn.bufnr(vim.fn.fnameescape(config.buffer_name))
+ local bufnr = vim.fn.bufnr(config.buffer_name)
```

**Comment by ej-shafran** [comment]
How interesting... I added the `fnameescape` to try and fix an issue with this exact thing. I'll give this another look and try to push a fix to nightly sometime today.

**Comment by ej-shafran** [comment]
Alright; finally managed to properly setup Windows in the CI, and the error is happening there. Will try to solve and hopefully the CI can act as a check for all platforms from now on.

**Comment by ej-shafran** [comment]
Ahh. This seems to summarize it pretty well:

https://github.com/neovim/neovim/issues/3912#issuecomment-167899148

I'll take a look at removing the `fnameescape` call, then. Maybe it's time to change the default compilation buffer name, as well, since these wildcards seem to only cause issues.

**Comment by ej-shafran** [comment]
Hiya. I believe the changes in 4.0.1 should fix your issue. Mind giving it a look and seeing that everything seems to be fine?

**Comment by vunhatchuong** [comment]
Fixed.
