### ISSUE TITLE
Feature Request: cmdwin file auto-completion 

### ISSUE THREAD

**Issue by odnal** [ej-shafran/compile-mode.nvim#24]
Hello, I really enjoy the plugin! I am not sure if this is just bug on my side or if it's not implemented. But I was curious if there was an implementation for the auto-completion of the file being parsed in the `Compile command:` buffer. The `<cmd>` seems to auto-complete but the `<file>` seems to not in something like this: `Compile command: <cmd> <file>`

**Comment by ej-shafran** [comment]
Yeah, I've actually been wanting to implement that for a while. Right now the command input uses the default Vim `shellcmd` completion, but I want to look into forwarding the completion to the shell itself so things like file names are properly completed. I'll try and implement this feature this week - you're also welcome to give it a shot if you'd like :)

**Comment by ej-shafran** [comment]
I've pushed changes to nightly that should implement this feature. Mind switching over to the nightly branch and seeing if it works for you?

**Comment by odnal** [comment]
Works nice! You beat me to it :)
