### ISSUE TITLE
[FEAT] Add User autocommand to notify finished compilation

### ISSUE THREAD

**Issue by Tonelllo** [ej-shafran/compile-mode.nvim#36]
### Emacs Interop

- [ ] This feature exists in Emacs' compilation mode
- [X] This feature would improve quality of life for all users

### Feature Suggestion

I am really liking this plugin so far.
I would find useful to have the possibility to run an autocommand when the compilation is finished but at the moment I don't see an easy way of doing so.

The easiest way I think would be to trigger an autocommand when The compilation is finished.
For example adding the following lines in "/lua/compile-mode/init.lua" line 286:

```lua
  vim.api.nvim_exec_autocmds("User", {
    pattern = "CompilationFinished",
    data = { CompileMessage = compilation_message },
  })
```

This is not a feature of Emacs' compilation-mode, but for what I could find it should be easily achievable by using an hook.

**Comment by ej-shafran** [comment]
Sounds totally fair. Will implement this.

**Comment by ej-shafran** [comment]
I've pushed to `nightly` with a change similar to what we discussed. Mind giving it a look and letting me know if it fits your usecase?

**Comment by Tonelllo** [comment]
Yes, it fits what I was asking perfectly. Fantastic job even with the documentation.
