### ISSUE TITLE
[FEAT]  `q` should close buffer without quitting neovim

### ISSUE THREAD

**Issue by immanelg** [ej-shafran/compile-mode.nvim#38]
### Emacs Interop

- [X] This feature exists in Emacs' compilation mode
- [X] This feature would improve quality of life for all users

### Feature Suggestion

```markdown
Currently `q` key executes `:q`. If there's only one window and it contains compilation buffer, `q` closes neovim which is annoying. Instead of that, `q` can execute `:bdelete`.
```

**Comment by ej-shafran** [comment]
Sure, I like this idea. Do you want to open a PR for this or should I?

**Comment by immanelg** [comment]
It should be an easy fix, you can do it youself if you want. I will be away from a computer for a while anyway.
