### ISSUE TITLE
[FEAT] Builtin neovim terminal for compilation buffer

### ISSUE THREAD

**Issue by immanelg** [ej-shafran/compile-mode.nvim#40]
### Emacs Interop

- [ ] This feature exists in Emacs' compilation mode
- [X] This feature would improve quality of life for all users

### Feature Suggestion

Compile-mode could send commands to a regular `:term` with something like this:
```lua
local compile_command = "make";
local chan = 7 -- channel of term buffer

vim.api.nvim_chan_send(7, "clear; ".."echo Compilation started "..os.date("%T").."\r")
vim.api.nvim_chan_send(7, compile_command.."\r")
```

instead of having a special buffer. 

It has some advantages:
- Compilers now print colors without issues, and we don't need to parse them (reimplementing a terminal)
- We can reuse this buffer as a regular terminal to execute other ad-hoc commands without reassigning :Compile command (and it still would be navigable by compile-mode keybindings)
- We can use a random terminal buffer as a compilation buffer, which would be navigable with compile-mode keybindings (instead of entering normal mode and jumping to a `file:line` and pressing `gF`)

**Comment by ej-shafran** [comment]
Yeah, I had considered this, but it seemed not hackable enough.

If what you're looking for is compilation keymaps to work anywhere, you can simply set a buffer's `filetype` to `compilation`, and errors should be parsed automatically.
