### ISSUE TITLE
[BUG] Plenary: attempt to call field 'list_contains' (a nil value)

### ISSUE THREAD

**Issue by maddeye** [ej-shafran/compile-mode.nvim#42]
### Existing Issues

- [X] I have searched the existing issues

### Describe the bug

When running `:Compile` or type `:Compile ` , this error shows up:

`Error executing Lua callback: ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...lazy/compile-mode.nvim/lua/compile-mode/config/check.lua:146: attempt to call field 'list_contains' (a
nil value)
stack traceback:
        [C]: in function 'error'
        ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
        ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:45: in function 'step'
        ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:48: in function 'execute'
        ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:118: in function <...share/nvim/lazy/plenary.nvim/lu
a/plenary/async/async.lua:117>`

### Steps To Reproduce

```markdown
1. Setup compiler-mode.nvim config
2. Install with Lazy
3. Run `:Compile` or type `:Compile `
```

### Expected Behavior

Complation buffer opens and output is shown

### Neovim Version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
```

### Plugin Version

```markdown
v5.3.0
```

### Configuration

```lua
return {
	"ej-shafran/compile-mode.nvim",
	tag = "v5.3.0",
	dependencies = {
		"nvim-lua/plenary.nvim",
		{ "m00qek/baleia.nvim", tag = "v1.3.0" },
	},
	config = function()
		---@type CompileModeOpts
		vim.g.compile_mode = {
			buffer_name = "compilation",
			-- to add ANSI escape code support, add:
			baleia_setup = true,
		}
	end,
}
```

### Additional Context

```markdown
I run on Debian 12 Bookworm on WSL2.
```

**Comment by ej-shafran** [comment]
Hmmm. Feel like this is probably an issue with the Neovim version. Will give this a look.

**Comment by ej-shafran** [comment]
Yup, v0.9.5 doesn't support `list_contains`, and a bunch of other things that `compile-mode.nvim` uses. Thinking I'll update the documentation to explain that the minimum supported version is v0.10.0, since I don't feel like reimplementing all of `vim.uv` and `vim.iter` on my own...
