### ISSUE TITLE
[FEAT] compile-mode.nvim and telescope.nvim

### ISSUE THREAD

**Issue by JNSFilipe** [ej-shafran/compile-mode.nvim#49]
### Emacs Interop

- [ ] This feature exists in Emacs' compilation mode
- [X] This feature would improve quality of life for all users

### Feature Suggestion

I am would like to trigger compile-mode.nvim from within a telescope.nvim callback, but this does not appear to work.

More specifically, in make case, I have a telescope picker that parses targets from Makefiles and lists them to the user within telescope. Then, I would like to trigger compile-mode.nvim based on the chosen target. This workflow exists in emacs.

**Comment by ej-shafran** [comment]
Hm. When you say "this doesn't appear to work", what do you mean? Can you share a minimal code snippet that you expect to work, but doesn't?

**Comment by ej-shafran** [comment]
This code snippet works:

```lua
local pickers = require("telescope.pickers")
local finders = require("telescope.finders")
local conf = require("telescope.config").values
local actions = require("telescope.actions")
local action_state = require("telescope.actions.state")
local compile_mode = require("compile-mode")

local commands = function(opts)
	opts = opts or {}
	pickers
		.new(opts, {
			prompt_title = "commands",
			finder = finders.new_table({
				"echo hi",
				"echo wow",
				"echo bye",
			}),
			sorter = conf.generic_sorter(opts),
			attach_mappings = function(prompt_bufnr, map)
				actions.select_default:replace(function()
					actions.close(prompt_bufnr)
					local selection = action_state.get_selected_entry()
					local command = selection[1]
					compile_mode.compile({ args = command, smods = {} })
				end)
				return true
			end,
		})
		:find()
end

commands()
```

(Am soon pushing a change to nightly that will make it possible to remove the `smods = {}` bit)

Is this not what you're looking for?

**Comment by ej-shafran** [comment]
With the change in #50, this following snippet now also works:

```lua
local pickers = require("telescope.pickers")
local finders = require("telescope.finders")
local conf = require("telescope.config").values
local actions = require("telescope.actions")
local action_state = require("telescope.actions.state")
local compile_mode = require("compile-mode")

local commands = function(opts)
	opts = opts or {}
	pickers
		.new(opts, {
			prompt_title = "commands",
			finder = finders.new_table({
				"echo hi",
				"echo wow",
				"echo bye",
			}),
			sorter = conf.generic_sorter(opts),
			attach_mappings = function(prompt_bufnr, map)
				actions.select_default:replace(function()
					actions.close(prompt_bufnr)
					local selection = action_state.get_selected_entry()
					local command = selection[1]
					compile_mode.compile({ args = command })
				end)
				return true
			end,
		})
		:find()
end

commands()
```

**Comment by JNSFilipe** [comment]
Ok, than you very much, both snippets are now working for me as well. I was trying to use something like `vim.cmd("Compile make " .. selection[1]")` before, and it was prompting me to save an unknown buffer and yielding different error, that is why I didn't include any error before.
Once again, thank you very much and I am sorry for my lack of skills!

**Comment by ej-shafran** [comment]
No need to apologize, friend! Glad to be of assistance.
